name: ddd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.24
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.1
  injectable: ^1.5.0

dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true
