name: ddd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_bloc: ^7.3.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.3
  cached_network_image: ^3.1.0
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
